#!/bin/bash

printUsage() {
	echo "Commands:
scan - scans for ssh connections
kill - kills ssh connections
exit - exits the program"
}

while true; do
	read -p "> " userIn
	case "${userIn}" in
		# w scans for logged on users
		# pipe that into grep and grep for local connections
		# pipe that into awk and check if the process is ssh
		# pipe that into ss and kill
		scan) w | grep -v localhost | awk 'match($8,"sshd:"){print $3} match($8,"w"){print $3}' ;; # scan for ssh connections
		kill) w | grep -v localhost | awk 'match($8,"sshd:"){print $3} match($8,"w"){print $3}' | ss -K ;; # kill ssh connections
		exit) exit 0 ;;
		*) printUsage ;;
	esac
done
